### ISSUE TITLE
Ability to Backup & Restore Rules

### ISSUE THREAD

**Issue by MuntashirAkon** [tuyafeng/Watt#1]
Ability to backup and restore rules can be very handy. DisableService (unfortunately, closed source) has this feature but it's not actively maintained and can only block services.

**Comment by tuyafeng** [comment]
All the rules are saved in the `/sdcard/Android/data/com.tuyafeng.watt/files/ifw` folder, you can simply copy the files to import or export.

**Comment by MuntashirAkon** [comment]
Thanks for the information.
