### ISSUE TITLE
Add documentation on how to use

### ISSUE THREAD

**Issue by MuntashirAkon** [tuyafeng/Watt#2]
After selecting an app, a new Activity is loaded containing three self explanatory tabs. However, it is not stated anywhere at all that clicking them disables them. There's also a button at the top and I don't know what it really does. There's also "Enable Preset" and "Disable All" in the menu and I don't know what they do for sure. My guess is "Disable All" is a misleading name.

Thanks.

**Comment by tuyafeng** [comment]
`Disable preset` Will disable all push components, `Enable all` will enable all disabled componets. It is worth mentioning that these operations will first request your confirmation. The circle button in the action bar is a switch to apply/cancel rules.
