### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [tuyafeng/Watt#3]
Hi,

Since this app is GNU GPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by tuyafeng** [comment]
I tried the build service of fdroid, but something went wrong with the buildserver, but when I checked the lzzyOnDroid repo, I found this package, which is also good.

**Comment by proletarius101** [comment]
@tuyafeng I've sent a PR here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7904. Just need your endorsement.

**Comment by proletarius101** [comment]
And it's recommanded but not compulsary to provide a fastlane-style metadata: https://gitlab.com/snippets/1895688

It can be easily generated (fetched) if you've submitted to Google Play. But you can also do a `fastlane init` and fill in the data.

**Comment by IzzySoft** [comment]
No need for the fastlane binaries (unless you want to use them). You can simply merge #6 to get Fastlane established :smiley: Of course, screenshots etc. are welcome; @proletarius101 already linked you my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) to get a quick overview.

**Comment by IzzySoft** [comment]
PS: once the app is listed at F-Droid.org, @tuyafeng – do you want me to keep it in my repo? See [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some decision help.

**Comment by tuyafeng** [comment]
> @tuyafeng I've sent a PR here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7904. Just needs your endorsement.

Thank you for submitting it for me, I totally agree.
