### ISSUE TITLE
Request for "Search component in all apps"

### ISSUE THREAD

**Issue by nkh0472** [tuyafeng/Watt#4]
请求添加“在所有app中搜索组件”功能。
对于关闭数百个应用的特定广告组件，这是最快速、最高效的办法。
感觉实现起来不算困难吧（大概），然而其他同类软件也没有这个功能。
这是我唯一让我摆脱不了MyAndroidTools的理由！
有了这个功能就终于可以摆脱各种bug的MAT了……

如果上述功能实现了，我愿称Watt为宇宙最强（hhh）

PS：实际上酷安MAT的评论区有很多关于通用广告组件的总结，我觉得这个可以作为一个可以在线更新的列表（内置）到app里。
实际上，维护通用广告组件的列表比维护特定应用甚至特定版本应用的难度要低的多，同时普适性要高得多。（出于规避某些风险的角度，这个列表或许应该作为社区维护的模式；app安装包内不应内置，仅提供下载入口即可）

**Comment by tuyafeng** [comment]
搜索组件等下回我有空了加上吧。组件管理那个，我倾向还是只将其作为一个纯粹的工具，保持门槛也是好事。
