### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [tuyafeng/Watt#7]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by tuyafeng** [comment]
Okay, I will add it later.

**Comment by mondlicht-und-sterne** [comment]
thank you very much

**Comment by tuyafeng** [comment]
fe73876 The fastline information has been completed.
